SELECT * FROM healthcare.healthcare;
#Retrieve the names of all patients in the database.
SELECT Name from healthcare.healthcare;
# List the unique medical conditions present in the dataset.
SELECT distinct Medical_Condition from healthcare.healthcare;
 #Find the total number of doctors in the healthcare system. 
 SELECT count(Doctor) from healthcare.healthcare;
# Retrieve the details of all female patients. 
SELECT * from healthcare.healthcare where Gender = 'Female';
# what is the average age of patients in the database.
SELECT avg(Age) from healthcare.healthcare;
# Identify the patients who have more than one medical condition. 
SELECT Name from healthcare.healthcare where Medical_Condition =1 group by Name having count(*)>1;
# List the names of all doctors. 
select doctor from healthcare.healthcare;
# Identify the most common medical condition among patients.
SELECT Medical_Condition,count(*) as frequency from healthcare.healthcare group by Medical_Condition order by frequency DESC ;
# Find the patients who are older than 60 years and have diabetes. 
SELECT Name from healthcare.healthcare where Age>60 and Medical_Condition ='Diabetes';
# Calculate the total revenue generated by the healthcare system.
SELECT sum(billing_amount) as total_revenue from healthcare.healthcare;
#Find the doctor with the oldest patient.
SELECT doctor,age from healthcare.healthcare order by age desc limit 1;
#Calculate the average duration of medical visits.
SELECT avg(duration) from healthcare.healthcare;
#Give the names of patients whose name starts with A. 
SELECT Name from healthcare.healthcare where  Name like 'a%';
#How many male and female patients are there in dataset. 
SELECT gender, count(gender)  as patients_count from healthcare.healthcare group by gender;
#how many patients are normal. 
SELECT  count(name) as normal_patients from healthcare.healthcare where medical_condition ='normal';
#how many patients are abnormal or Inconclusive.
SELECT count(Medical_Condition) as abnormal_patients from healthcare.healthcare;
#how many patients of blood group AB+ are there of age above 52. 
SELECT count(blood_type) as 'AB+' from healthcare.healthcare where Blood_Type = 'AB+' and  age>52;
#how many patients have paid the bill above 24890. 
SELECT count(name) as paid from healthcare.healthcare where Billing_Amount > 24890;
# what are the names of patients having Asthma. 
SELECT  name from healthcare.healthcare where Medical_Condition ='Asthma' ;
# how many patients have cancer. 
SELECT count(medical_condition) as cancer from healthcare.healthcare where medical_condition = 'cancer';
# what are the names and blood groups of patients admitted to room no. 292. 
SELECT name ,blood_type from healthcare.healthcare where Room_Number = 292;
# how many males have Arthritis.
SELECT count(gender) as male_Arthritis from c where Medical_Condition = 'Arthritis' and gender ='male';
# How many patients were admitted to Harris and Sons hospital. 
SELECT count(name) as 'Harris and Sons_hospital' from healthcare.healthcare where Hospital='Harris and Sons';
# what are the names of patients whose Insurance Provider are Cigna. 
SELECT name from healthcare.healthcare where Insurance_Provider ='Cigna';
# Name the Medical Condition having patients whose ages is greater than average age
SELECT medical_condition from healthcare.healthcare group by medical_condition having avg(age)<(select avg(age)  from healthcare.healthcare);